image: jangrewe/gitlab-ci-android

stages:
  - build
  - deploy

before_script:
  - echo $PUBLISH_KEY > keys/publish-key.json

  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

  - export LIGHT_ALARM_BUILD_NUMBER=$CI_PIPELINE_IID

build:
  stage: build
  only:
    - branches
  script:
    - ./gradlew build lintRelease --no-daemon --console=plain --stacktrace --info
  artifacts:
    paths:
      - build/outputs/

masterBuild:
  stage: deploy
  script:
    - ./gradlew publishReleaseBundle --no-daemon --console=plain
  only:
    - master
