[versions]
kotlin = "1.7.20"
firebase = "30.5.0"
dagger = "2.44"
coroutines = "1.6.4"

[libraries]
android-build-gradle = { module = "com.android.tools.build:gradle", version = "7.3.0"}
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin"}

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version = "1.0.0" }

material = { module = "com.google.android.material:material", version = "1.6.1" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger"}
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

timber = { module = "com.jakewharton.timber:timber", version = "5.0.1"}
paper = { module = "io.github.pilgr:paperdb", version = "2.7.2" }

mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version = "2.2.0" }
truth = { module = "com.google.truth:truth", version = "1.1.3"}

[bundles]
buildSrc = [
    "android-build-gradle",
    "kotlin-gradle-plugin",
]

[plugins]
version-check = { id = "com.github.ben-manes.versions", version = "0.42.0" }
play-publisher = { id = "com.github.triplet.play", version = "3.7.0"}
google-services = { id = "com.google.gms.google-services", version = "4.3.14" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.8.1" }
ksp = { id = "com.google.devtools.ksp", version = "1.7.20-1.0.6" }
